### ISSUE TITLE
[Web] Add React Hooks Support

### ISSUE THREAD

**Issue by artalat** [BlueBaseJS/cli#52]
Components with React Hooks API currently don't work in web projects (they work fine in other cli platforms i.e. storybook, expo, etc). This may be because web platform is using an older version of React. This needs to be investigated and fixed.

**Comment by danial24** [comment]
@artalat 
Resolved this issue.
Here is the PR 
https://github.com/BlueBaseJS/cli/pull/106

**Comment by artalat** [comment]
closed by #107
